sudo: false
language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile

before_install:
  - gem update --system
  - gem update bundler

cache: bundler

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_edge.gemfile

  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
