sudo: false
language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
before_install:
  - gem update --system
  - gem install bundler -v '< 2.0'
cache: bundler
notifications:
  email:
    on_success: never
    on_failure: change
